### ISSUE TITLE
maybe disable issues tab and in readme point people to discussions tab?

### ISSUE THREAD

**Issue by derberg** [APIs-Working-Group/proposals#1]

**Comment by MikeRalphson** [comment]
Your thinking is?

**Comment by derberg** [comment]
readme says `Proposals for spec. or tooling solutions`

so goal of repo is more to discuss things, ideas. Probably look at emoticons reactions of popularity + would be good to have "vote up" functionality. So something that is better for `Discussions`. If you leave `Issues` people, biased by their experience will sometimes go to issues and sometimes to discussions (of course you can maintain and cleanup)

**Comment by MikeRalphson** [comment]
Closing so I can disable the issues tab. Great idea, thanks.
